kmiri: fix in-bounds pointer arithmetic UB using integer arithmetic
error: Undefined Behavior: in-bounds pointer arithmetic failed: attempting to offset pointer by 16 bytes, but got alloc769198 which is only 8 bytes from the
end of the allocation
   --> /home/zjp/KMiri/asterinas/ostd/src/mm/page_table/boot_pt.rs:193:32
    |
193 |         let pte_ptr = unsafe { (paddr_to_vaddr(pt) as *mut E).add(index) };
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Undefined Behavior occurred here
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
help: alloc769198 was allocated here:
   --> src/main.rs:18:5
    |
 18 |     ostd::arch::boot::miri_boot();
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: stack backtrace:
            0: ostd::mm::page_table::boot_pt::BootPageTable::map_base_page
                at /home/zjp/KMiri/asterinas/ostd/src/mm/page_table/boot_pt.rs:193:32: 193:73
            1: ostd::mm::frame::meta::init::{closure#2}
                at /home/zjp/KMiri/asterinas/ostd/src/mm/frame/meta.rs:490:22: 490:69
            2: ostd::mm::page_table::boot_pt::with_borrow::<{closure@ostd::mm::frame::meta::init::{closure#2}}, ()>
                at /home/zjp/KMiri/asterinas/ostd/src/mm/page_table/boot_pt.rs:57:13: 57:41
            3: ostd::mm::frame::meta::init
                at /home/zjp/KMiri/asterinas/ostd/src/mm/frame/meta.rs:480:5: 492:7
            4: ostd::init
                at /home/zjp/KMiri/asterinas/ostd/src/lib.rs:135:31: 135:54
            5: ostd::boot::start_kernel
                at /home/zjp/KMiri/asterinas/ostd/src/boot/mod.rs:138:14: 138:27
            6: ostd::arch::boot::miri_boot
                at /home/zjp/KMiri/asterinas/ostd/src/arch/miri/boot/mod.rs:73:14: 73:28
            7: miri_start
                at src/main.rs:18:5: 18:34