kmiri(osdk): replace start by main
error[E0557]: feature has been removed
 --> src/main.rs:2:27
  |
2 | #![cfg_attr(miri, feature(start))]
  |                           ^^^^^ feature has been removed
  |
  = note: removed in 1.86.0; see <https://github.com/rust-lang/rust/pull/134299> for more information
  = note: not portable enough and never RFC'd