kmiri: fix pointer out-of-bound UB in alloc_meta_frames
`ptr.add(n)` requires the same allocation, so we use integer arithmetic
to bypass the requirement and avoid the UB

error: Undefined Behavior: in-bounds pointer arithmetic failed: attempting to offset pointer by 128 bytes, but got alloc10351 which is only 64 bytes from the end of the allocation
   --> /home/zjp/KMiri/asterinas/ostd/src/mm/frame/meta.rs:554:29
    |
554 |         let slot = unsafe { slots.add(i) };
    |                             ^^^^^^^^^^^^ Undefined Behavior occurred here
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
help: alloc10351 was allocated here:
   --> src/main.rs:18:5
    |
 18 |     ostd::arch::boot::miri_boot();
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: stack backtrace:
            0: ostd::mm::frame::meta::alloc_meta_frames
                at /home/zjp/KMiri/asterinas/ostd/src/mm/frame/meta.rs:554:29: 554:41
            1: ostd::mm::frame::meta::init
                at /home/zjp/KMiri/asterinas/ostd/src/mm/frame/meta.rs:477:39: 477:71
            2: ostd::init
                at /home/zjp/KMiri/asterinas/ostd/src/lib.rs:135:31: 135:54
            3: ostd::boot::start_kernel
                at /home/zjp/KMiri/asterinas/ostd/src/boot/mod.rs:138:14: 138:27
            4: ostd::arch::boot::miri_boot
                at /home/zjp/KMiri/asterinas/ostd/src/arch/miri/boot/mod.rs:73:14: 73:28
            5: miri_start
                at src/main.rs:18:5: 18:34